# Generated by Django 4.2.1 on 2023-05-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('file_data', models.FileField(upload_to='')),
                ('response', models.JSONField(null=True)),
                ('is_scanned', models.BooleanField(default=False)),
            ],
        ),
    ]
