# Generated by Django 4.2.1 on 2023-05-15 23:35

from django.db import migrations, models
import holder.models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='uniq_id',
            field=models.CharField(default=holder.models.generate_uniq_id, max_length=100),
        ),
    ]
