# Generated by Django 4.2.1 on 2023-05-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0002_queue_uniq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='file_data',
            field=models.FileField(upload_to='uploaded_files'),
        ),
    ]
