# Generated by Django 4.2.1 on 2023-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0003_alter_queue_file_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='file_name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
