# Generated by Django 4.2.1 on 2023-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0004_queue_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
    ]
