# Generated by Django 4.2.1 on 2023-06-11 16:39

from django.db import migrations, models
import holder.models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0005_queue_has_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_uuid', models.CharField(default=holder.models.generate_uniq_id, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
