# Generated by Django 4.2.1 on 2023-06-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0006_user_queue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holder.user'),
        ),
    ]
